board(0,b(b,e,b,w,b,e,e,w,w)).
board(1,b(e,b,b,b,w,e,w,e,w)).
board(2,b(b,e,b,b,e,e,e,w,w)).
board(3,b(b,b,e,w,e,b,e,w,w)).
board(4,b(b,e,b,w,b,e,e,w,w)).
board(5,b(b,b,e,w,e,b,e,w,w)).
board(6,b(e,b,b,e,b,e,w,e,w)).
board(7,b(b,e,b,w,b,e,e,w,w)).
board(8,b(e,b,b,b,w,e,w,e,w)).
board(9,b(e,b,b,e,b,e,w,e,w)).
board(10,b(b,b,e,w,e,b,e,w,w)).
board(11,b(e,b,b,e,b,e,w,e,w)).
board(12,b(b,b,e,w,e,b,e,w,w)).
board(13,b(b,b,e,w,e,b,e,w,w)).
board(14,b(b,e,b,w,b,e,e,w,w)).
board(15,b(b,e,b,w,b,e,e,w,w)).
board(16,b(e,b,b,b,w,e,w,e,w)).
board(17,b(e,b,b,e,b,e,w,e,w)).
board(18,b(b,e,b,w,b,e,e,w,w)).
board(19,b(b,b,e,w,e,b,e,w,w)).
board(20,b(b,b,e,w,e,b,e,w,w)).
board(21,b(e,b,b,e,b,e,w,e,w)).
board(22,b(b,e,b,b,e,e,e,w,w)).
board(23,b(b,e,b,w,b,e,e,w,w)).
board(24,b(e,b,b,b,w,e,w,e,w)).
board(25,b(e,b,b,b,w,e,w,e,w)).
board(26,b(b,e,b,b,e,e,e,w,w)).
board(27,b(e,b,b,e,b,e,w,e,w)).
board(28,b(b,b,e,w,e,b,e,w,w)).
board(29,b(e,b,b,b,w,e,w,e,w)).
board(30,b(b,b,e,w,e,b,e,w,w)).
board(31,b(b,e,b,w,b,e,e,w,w)).
board(32,b(e,b,b,b,w,e,w,e,w)).
board(33,b(b,e,b,w,b,e,e,w,w)).
board(34,b(e,b,b,b,w,e,w,e,w)).
board(35,b(e,b,b,e,b,e,w,e,w)).
board(36,b(b,e,b,w,b,e,e,w,w)).
board(37,b(e,b,b,e,b,e,w,e,w)).
board(38,b(b,b,e,w,e,b,e,w,w)).
board(39,b(b,e,b,b,e,e,e,w,w)).
board(40,b(b,b,e,w,e,b,e,w,w)).
board(41,b(e,b,b,e,b,e,w,e,w)).
board(42,b(b,e,b,w,b,e,e,w,w)).
board(43,b(e,b,b,b,w,e,w,e,w)).
board(44,b(b,e,b,w,b,e,e,w,w)).
board(45,b(b,e,b,b,e,e,e,w,w)).
board(46,b(b,e,b,w,b,e,e,w,w)).
board(47,b(b,e,b,w,b,e,e,w,w)).
board(48,b(b,b,e,w,e,b,e,w,w)).
board(49,b(b,e,b,w,b,e,e,w,w)).
board(50,b(b,b,e,w,e,b,e,w,w)).
board(51,b(b,e,b,w,b,e,e,w,w)).
board(52,b(b,b,e,w,e,b,e,w,w)).
board(53,b(b,e,b,b,e,e,e,w,w)).
board(54,b(b,b,e,w,e,b,e,w,w)).
board(55,b(e,b,b,b,w,e,w,e,w)).
board(56,b(e,b,b,b,w,e,w,e,w)).
board(57,b(e,b,b,b,w,e,w,e,w)).
board(58,b(e,b,b,b,w,e,w,e,w)).
board(59,b(e,b,b,b,w,e,w,e,w)).
board(60,b(b,b,e,w,e,b,e,w,w)).
board(61,b(b,b,e,w,e,b,e,w,w)).
board(62,b(e,b,b,b,w,e,w,e,w)).
board(63,b(b,e,b,w,b,e,e,w,w)).
board(64,b(b,b,e,w,e,b,e,w,w)).
board(65,b(b,b,e,w,e,b,e,w,w)).
board(66,b(b,e,b,w,b,e,e,w,w)).
board(67,b(e,b,b,b,w,e,w,e,w)).
board(68,b(b,e,b,b,e,e,e,w,w)).
board(69,b(b,e,b,w,b,e,e,w,w)).
board(70,b(b,b,e,w,e,b,e,w,w)).
board(71,b(b,e,b,b,e,e,e,w,w)).
board(72,b(b,b,e,w,e,b,e,w,w)).
board(73,b(b,e,b,w,b,e,e,w,w)).
board(74,b(e,b,b,b,w,e,w,e,w)).
board(75,b(b,e,b,b,e,e,e,w,w)).
board(76,b(b,e,b,b,e,e,e,w,w)).
board(77,b(e,b,b,b,w,e,w,e,w)).
board(78,b(e,b,b,e,b,e,w,e,w)).
board(79,b(e,b,b,b,w,e,w,e,w)).
board(80,b(e,b,b,e,b,e,w,e,w)).
board(81,b(b,e,b,b,e,e,e,w,w)).
board(82,b(b,e,b,b,e,e,e,w,w)).
board(83,b(e,b,b,e,b,e,w,e,w)).
board(84,b(e,b,b,b,w,e,w,e,w)).
board(85,b(e,b,b,e,b,e,w,e,w)).
board(86,b(b,e,b,w,b,e,e,w,w)).
board(87,b(b,e,b,w,b,e,e,w,w)).
board(88,b(e,b,b,b,w,e,w,e,w)).
board(89,b(b,e,b,w,b,e,e,w,w)).
board(90,b(b,e,b,w,b,e,e,w,w)).
board(91,b(e,b,b,e,b,e,w,e,w)).
board(92,b(b,b,e,w,e,b,e,w,w)).
board(93,b(b,b,e,w,e,b,e,w,w)).
board(94,b(e,b,b,e,b,e,w,e,w)).
board(95,b(b,e,b,b,e,e,e,w,w)).
board(96,b(b,e,b,b,e,e,e,w,w)).
board(97,b(e,b,b,e,b,e,w,e,w)).
board(98,b(e,b,b,b,w,e,w,e,w)).
board(99,b(b,e,b,b,e,e,e,w,w)).
