board(0,b(e,e,e,e,e,e,e,o,x)).
board(1,b(e,e,x,e,e,e,o,e,e)).
board(2,b(e,e,e,e,e,e,e,x,o)).
board(3,b(e,e,e,e,e,o,e,x,e)).
board(4,b(e,e,e,e,x,e,e,e,o)).
board(5,b(e,e,e,e,e,e,e,o,x)).
board(6,b(e,e,e,e,e,o,x,e,e)).
board(7,b(e,e,e,e,e,e,e,x,o)).
board(8,b(e,e,e,e,o,e,e,e,x)).
board(9,b(e,e,e,e,o,e,e,e,x)).
board(10,b(e,e,e,o,e,x,e,e,e)).
board(11,b(e,e,x,e,e,e,o,e,e)).
board(12,b(e,e,e,e,e,e,e,o,x)).
board(13,b(e,e,e,o,e,x,e,e,e)).
board(14,b(e,e,e,e,o,e,e,x,e)).
board(15,b(e,e,e,e,e,o,x,e,e)).
board(16,b(e,e,e,e,e,e,o,e,x)).
board(17,b(e,e,x,e,e,e,o,e,e)).
board(18,b(e,e,e,e,e,x,o,e,e)).
board(19,b(e,e,e,e,x,e,e,o,e)).
board(20,b(e,e,e,e,o,e,e,e,x)).
board(21,b(e,e,e,o,e,x,e,e,e)).
board(22,b(e,e,e,e,x,e,e,e,o)).
board(23,b(e,e,e,e,o,e,e,x,e)).
board(24,b(e,e,e,e,e,e,e,o,x)).
board(25,b(e,e,e,e,e,e,e,x,o)).
board(26,b(e,e,x,e,e,e,o,e,e)).
board(27,b(e,e,e,e,o,e,e,e,x)).
board(28,b(e,e,e,e,e,e,e,x,o)).
board(29,b(e,e,e,e,e,o,x,e,e)).
board(30,b(e,e,e,e,e,e,e,x,o)).
board(31,b(e,e,e,e,o,e,e,x,e)).
board(32,b(e,e,e,e,e,x,o,e,e)).
board(33,b(e,e,e,e,e,o,e,x,e)).
board(34,b(e,e,e,e,e,x,o,e,e)).
board(35,b(e,e,e,e,x,e,e,e,o)).
board(36,b(e,e,e,e,x,e,e,e,o)).
board(37,b(e,e,e,e,e,o,e,x,e)).
board(38,b(e,e,e,e,x,e,e,o,e)).
board(39,b(e,e,e,e,x,e,e,o,e)).
board(40,b(e,e,e,e,x,e,e,e,o)).
board(41,b(e,e,x,e,e,e,o,e,e)).
board(42,b(e,e,e,e,e,e,o,e,x)).
board(43,b(e,e,e,e,e,x,o,e,e)).
board(44,b(e,e,e,e,e,x,o,e,e)).
board(45,b(e,e,e,e,e,e,e,x,o)).
board(46,b(e,e,e,e,e,x,o,e,e)).
board(47,b(e,e,e,e,e,o,e,x,e)).
board(48,b(e,e,x,e,e,e,o,e,e)).
board(49,b(e,e,e,e,e,e,e,x,o)).
board(50,b(e,e,e,e,x,e,e,e,o)).
board(51,b(e,e,e,e,o,e,e,e,x)).
board(52,b(e,e,x,e,e,e,o,e,e)).
board(53,b(e,e,e,e,e,x,o,e,e)).
board(54,b(e,e,e,e,e,e,o,e,x)).
board(55,b(e,e,e,e,e,x,o,e,e)).
board(56,b(e,e,e,o,e,x,e,e,e)).
board(57,b(e,e,e,e,x,e,e,e,o)).
board(58,b(e,e,e,e,o,e,e,e,x)).
board(59,b(e,e,e,e,x,e,e,e,o)).
board(60,b(e,e,e,e,e,o,e,x,e)).
board(61,b(e,e,e,e,e,e,e,o,x)).
board(62,b(e,e,e,e,x,e,e,o,e)).
board(63,b(e,e,e,o,e,x,e,e,e)).
board(64,b(e,e,e,e,e,e,o,e,x)).
board(65,b(e,e,e,e,e,o,x,e,e)).
board(66,b(e,e,e,e,e,e,e,o,x)).
board(67,b(e,e,e,e,e,e,e,x,o)).
board(68,b(e,e,e,e,e,e,e,o,x)).
board(69,b(e,e,e,e,e,o,x,e,e)).
board(70,b(e,e,e,e,o,e,e,e,x)).
board(71,b(e,e,e,e,e,e,e,x,o)).
board(72,b(e,e,e,e,e,o,x,e,e)).
board(73,b(e,e,e,o,e,x,e,e,e)).
board(74,b(e,e,e,e,e,e,e,o,x)).
board(75,b(e,e,e,e,e,e,e,o,x)).
board(76,b(e,e,e,e,e,o,e,x,e)).
board(77,b(e,e,e,e,o,e,e,e,x)).
board(78,b(e,e,e,e,o,e,e,e,x)).
board(79,b(e,e,e,e,x,e,e,o,e)).
board(80,b(e,e,e,e,e,o,x,e,e)).
board(81,b(e,e,e,e,e,o,x,e,e)).
board(82,b(e,e,e,e,e,e,o,e,x)).
board(83,b(e,e,e,e,o,e,e,x,e)).
board(84,b(e,e,e,o,e,x,e,e,e)).
board(85,b(e,e,e,e,e,o,e,x,e)).
board(86,b(e,e,e,e,x,e,e,o,e)).
board(87,b(e,e,e,e,e,e,o,e,x)).
board(88,b(e,e,e,e,o,e,e,x,e)).
board(89,b(e,e,e,e,o,e,e,e,x)).
board(90,b(e,e,e,e,e,o,x,e,e)).
board(91,b(e,e,e,e,e,o,e,x,e)).
board(92,b(e,e,e,e,e,x,o,e,e)).
board(93,b(e,e,x,e,e,e,o,e,e)).
board(94,b(e,e,e,e,e,x,o,e,e)).
board(95,b(e,e,x,e,e,e,o,e,e)).
board(96,b(e,e,e,e,x,e,e,e,o)).
board(97,b(e,e,e,e,o,e,e,e,x)).
board(98,b(e,e,x,e,e,e,o,e,e)).
board(99,b(e,e,e,e,e,o,e,x,e)).
board(100,b(e,e,e,e,o,e,e,x,e)).
board(101,b(e,e,e,e,e,e,e,o,x)).
board(102,b(e,e,e,e,o,e,e,x,e)).
board(103,b(e,e,e,e,e,o,x,e,e)).
board(104,b(e,e,e,e,e,o,e,x,e)).
board(105,b(e,e,e,o,e,x,e,e,e)).
board(106,b(e,e,e,e,o,e,e,e,x)).
board(107,b(e,e,e,e,e,e,e,x,o)).
board(108,b(e,e,e,e,e,o,e,x,e)).
board(109,b(e,e,e,o,e,x,e,e,e)).
board(110,b(e,e,e,e,o,e,e,x,e)).
board(111,b(e,e,e,o,e,x,e,e,e)).
board(112,b(e,e,e,e,x,e,e,e,o)).
board(113,b(e,e,x,e,e,e,o,e,e)).
board(114,b(e,e,e,e,x,e,e,o,e)).
board(115,b(e,e,x,e,e,e,o,e,e)).
board(116,b(e,e,e,o,e,x,e,e,e)).
board(117,b(e,e,e,e,e,o,e,x,e)).
board(118,b(e,e,e,e,e,e,e,x,o)).
board(119,b(e,e,e,e,e,x,o,e,e)).
board(120,b(e,e,e,e,o,e,e,x,e)).
board(121,b(e,e,e,e,e,e,e,x,o)).
board(122,b(e,e,e,e,o,e,e,e,x)).
board(123,b(e,e,e,e,x,e,e,o,e)).
board(124,b(e,e,e,e,x,e,e,e,o)).
board(125,b(e,e,e,e,o,e,e,e,x)).
board(126,b(e,e,e,e,e,e,o,e,x)).
board(127,b(e,e,e,e,x,e,e,e,o)).
board(128,b(e,e,e,e,e,e,e,o,x)).
board(129,b(e,e,e,e,o,e,e,e,x)).
board(130,b(e,e,e,e,o,e,e,e,x)).
board(131,b(e,e,e,e,e,x,o,e,e)).
board(132,b(e,e,e,e,x,e,e,o,e)).
board(133,b(e,e,e,e,o,e,e,e,x)).
board(134,b(e,e,e,e,e,x,o,e,e)).
board(135,b(e,e,e,e,x,e,e,e,o)).
board(136,b(e,e,e,e,e,x,o,e,e)).
board(137,b(e,e,e,e,e,e,o,e,x)).
board(138,b(e,e,e,e,e,o,e,x,e)).
board(139,b(e,e,x,e,e,e,o,e,e)).
board(140,b(e,e,e,e,e,e,o,e,x)).
board(141,b(e,e,e,e,x,e,e,e,o)).
board(142,b(e,e,e,e,e,e,e,x,o)).
board(143,b(e,e,x,e,e,e,o,e,e)).
board(144,b(e,e,e,e,e,o,e,x,e)).
board(145,b(e,e,e,e,e,e,o,e,x)).
board(146,b(e,e,e,e,e,o,e,x,e)).
board(147,b(e,e,x,e,e,e,o,e,e)).
board(148,b(e,e,e,o,e,x,e,e,e)).
board(149,b(e,e,e,e,e,x,o,e,e)).
board(150,b(e,e,e,e,o,e,e,x,e)).
board(151,b(e,e,x,e,e,e,o,e,e)).
board(152,b(e,e,e,e,x,e,e,e,o)).
board(153,b(e,e,e,e,o,e,e,e,x)).
board(154,b(e,e,e,e,e,o,x,e,e)).
board(155,b(e,e,e,e,e,o,x,e,e)).
board(156,b(e,e,e,e,e,e,e,o,x)).
board(157,b(e,e,e,e,e,o,e,x,e)).
board(158,b(e,e,x,e,e,e,o,e,e)).
board(159,b(e,e,e,e,o,e,e,e,x)).
board(160,b(e,e,e,e,x,e,e,e,o)).
board(161,b(e,e,e,e,e,e,e,o,x)).
board(162,b(e,e,x,e,e,e,o,e,e)).
board(163,b(e,e,e,e,e,e,o,e,x)).
board(164,b(e,e,e,o,e,x,e,e,e)).
board(165,b(e,e,x,e,e,e,o,e,e)).
board(166,b(e,e,e,e,o,e,e,e,x)).
board(167,b(e,e,e,e,x,e,e,o,e)).
board(168,b(e,e,e,e,e,e,o,e,x)).
board(169,b(e,e,e,e,x,e,e,e,o)).
board(170,b(e,e,x,e,e,e,o,e,e)).
board(171,b(e,e,e,o,e,x,e,e,e)).
board(172,b(e,e,e,e,o,e,e,x,e)).
board(173,b(e,e,e,e,e,x,o,e,e)).
board(174,b(e,e,e,e,x,e,e,e,o)).
board(175,b(e,e,e,e,e,o,x,e,e)).
board(176,b(e,e,e,e,o,e,e,e,x)).
board(177,b(e,e,e,e,x,e,e,o,e)).
board(178,b(e,e,e,e,e,o,x,e,e)).
board(179,b(e,e,e,e,x,e,e,o,e)).
board(180,b(e,e,e,e,o,e,e,e,x)).
board(181,b(e,e,e,e,x,e,e,e,o)).
board(182,b(e,e,e,e,e,o,e,x,e)).
board(183,b(e,e,e,e,e,e,e,x,o)).
board(184,b(e,e,e,e,e,o,e,x,e)).
board(185,b(e,e,e,e,o,e,e,e,x)).
board(186,b(e,e,x,e,e,e,o,e,e)).
board(187,b(e,e,e,e,o,e,e,x,e)).
board(188,b(e,e,e,e,e,o,e,x,e)).
board(189,b(e,e,e,e,e,e,e,o,x)).
board(190,b(e,e,e,e,e,e,e,x,o)).
board(191,b(e,e,e,e,o,e,e,x,e)).
board(192,b(e,e,x,e,e,e,o,e,e)).
board(193,b(e,e,e,e,e,o,x,e,e)).
board(194,b(e,e,e,o,e,x,e,e,e)).
board(195,b(e,e,e,e,e,e,e,x,o)).
board(196,b(e,e,e,o,e,x,e,e,e)).
board(197,b(e,e,x,e,e,e,o,e,e)).
board(198,b(e,e,e,e,o,e,e,x,e)).
board(199,b(e,e,x,e,e,e,o,e,e)).
