board(0,b(b,e,b,b,e,b,e,e,w,e,e,e,e,w,w,w)).
board(1,b(e,b,b,b,b,e,e,e,e,e,w,e,w,w,e,w)).
board(2,b(b,e,b,b,e,b,e,e,w,e,e,e,e,w,w,w)).
board(3,b(b,b,b,e,e,e,e,b,e,w,e,e,w,e,w,w)).
board(4,b(b,e,b,b,e,b,e,e,e,e,e,w,w,w,w,e)).
board(5,b(e,b,b,b,b,e,e,e,e,w,e,e,w,e,w,w)).
board(6,b(b,b,b,e,e,e,e,b,e,e,e,w,w,w,w,e)).
board(7,b(b,b,e,b,e,e,b,e,e,w,e,e,w,e,w,w)).
board(8,b(b,e,b,b,e,b,e,e,w,e,e,e,e,w,w,w)).
board(9,b(b,b,e,b,e,e,b,e,e,e,w,e,w,w,e,w)).
board(10,b(b,b,e,b,e,e,b,e,e,e,w,e,w,w,e,w)).
board(11,b(b,b,e,b,e,e,b,e,e,e,e,w,w,w,w,e)).
board(12,b(b,b,b,e,e,e,e,b,e,e,e,w,w,w,w,e)).
board(13,b(b,b,e,b,e,e,b,e,e,w,e,e,w,e,w,w)).
board(14,b(b,e,b,b,e,b,e,e,w,e,e,e,e,w,w,w)).
board(15,b(b,e,b,b,e,b,e,e,e,e,w,e,w,w,e,w)).
board(16,b(e,b,b,b,b,e,e,e,w,e,e,e,e,w,w,w)).
board(17,b(b,e,b,b,e,b,e,e,e,w,e,e,w,e,w,w)).
board(18,b(b,b,b,e,e,e,e,b,e,w,e,e,w,e,w,w)).
board(19,b(b,b,e,b,e,e,b,e,e,e,e,w,w,w,w,e)).
board(20,b(e,b,b,b,b,e,e,e,e,w,e,e,w,e,w,w)).
board(21,b(e,b,b,b,b,e,e,e,e,e,e,w,w,w,w,e)).
board(22,b(b,e,b,b,e,b,e,e,w,e,e,e,e,w,w,w)).
board(23,b(b,e,b,b,e,b,e,e,e,e,w,e,w,w,e,w)).
board(24,b(b,e,b,b,e,b,e,e,e,e,e,w,w,w,w,e)).
board(25,b(b,b,e,b,e,e,b,e,e,e,w,e,w,w,e,w)).
board(26,b(b,b,b,e,e,e,e,b,w,e,e,e,e,w,w,w)).
board(27,b(e,b,b,b,b,e,e,e,w,e,e,e,e,w,w,w)).
board(28,b(e,b,b,b,b,e,e,e,w,e,e,e,e,w,w,w)).
board(29,b(b,b,e,b,e,e,b,e,e,e,e,w,w,w,w,e)).
board(30,b(b,b,b,e,e,e,e,b,e,e,w,e,w,w,e,w)).
board(31,b(b,b,b,e,e,e,e,b,w,e,e,e,e,w,w,w)).
board(32,b(e,b,b,b,b,e,e,e,e,e,e,w,w,w,w,e)).
board(33,b(b,b,b,e,e,e,e,b,e,w,e,e,w,e,w,w)).
board(34,b(b,b,e,b,e,e,b,e,w,e,e,e,e,w,w,w)).
board(35,b(b,b,b,e,e,e,e,b,e,e,w,e,w,w,e,w)).
board(36,b(e,b,b,b,b,e,e,e,e,e,w,e,w,w,e,w)).
board(37,b(e,b,b,b,b,e,e,e,e,e,w,e,w,w,e,w)).
board(38,b(b,e,b,b,e,b,e,e,w,e,e,e,e,w,w,w)).
board(39,b(b,b,e,b,e,e,b,e,e,e,e,w,w,w,w,e)).
board(40,b(b,b,b,e,e,e,e,b,e,e,e,w,w,w,w,e)).
board(41,b(b,e,b,b,e,b,e,e,e,w,e,e,w,e,w,w)).
board(42,b(b,e,b,b,e,b,e,e,e,w,e,e,w,e,w,w)).
board(43,b(e,b,b,b,b,e,e,e,w,e,e,e,e,w,w,w)).
board(44,b(e,b,b,b,b,e,e,e,e,e,w,e,w,w,e,w)).
board(45,b(b,e,b,b,e,b,e,e,e,w,e,e,w,e,w,w)).
board(46,b(b,e,b,b,e,b,e,e,e,e,w,e,w,w,e,w)).
board(47,b(e,b,b,b,b,e,e,e,e,w,e,e,w,e,w,w)).
board(48,b(b,b,e,b,e,e,b,e,w,e,e,e,e,w,w,w)).
board(49,b(e,b,b,b,b,e,e,e,e,w,e,e,w,e,w,w)).
board(50,b(b,b,e,b,e,e,b,e,e,e,e,w,w,w,w,e)).
board(51,b(b,e,b,b,e,b,e,e,e,e,w,e,w,w,e,w)).
board(52,b(b,e,b,b,e,b,e,e,e,e,w,e,w,w,e,w)).
board(53,b(b,b,e,b,e,e,b,e,e,w,e,e,w,e,w,w)).
board(54,b(e,b,b,b,b,e,e,e,e,e,w,e,w,w,e,w)).
board(55,b(b,b,b,e,e,e,e,b,e,w,e,e,w,e,w,w)).
board(56,b(b,b,b,e,e,e,e,b,e,e,e,w,w,w,w,e)).
board(57,b(b,e,b,b,e,b,e,e,w,e,e,e,e,w,w,w)).
board(58,b(b,e,b,b,e,b,e,e,w,e,e,e,e,w,w,w)).
board(59,b(b,b,e,b,e,e,b,e,e,e,e,w,w,w,w,e)).
board(60,b(b,b,b,e,e,e,e,b,e,e,w,e,w,w,e,w)).
board(61,b(b,e,b,b,e,b,e,e,e,w,e,e,w,e,w,w)).
board(62,b(b,e,b,b,e,b,e,e,e,w,e,e,w,e,w,w)).
board(63,b(b,b,e,b,e,e,b,e,e,w,e,e,w,e,w,w)).
board(64,b(b,b,b,e,e,e,e,b,w,e,e,e,e,w,w,w)).
board(65,b(e,b,b,b,b,e,e,e,e,e,e,w,w,w,w,e)).
board(66,b(b,b,e,b,e,e,b,e,e,e,w,e,w,w,e,w)).
board(67,b(b,e,b,b,e,b,e,e,e,w,e,e,w,e,w,w)).
board(68,b(e,b,b,b,b,e,e,e,w,e,e,e,e,w,w,w)).
board(69,b(b,e,b,b,e,b,e,e,e,e,w,e,w,w,e,w)).
board(70,b(e,b,b,b,b,e,e,e,e,e,e,w,w,w,w,e)).
board(71,b(e,b,b,b,b,e,e,e,w,e,e,e,e,w,w,w)).
board(72,b(b,b,e,b,e,e,b,e,e,e,e,w,w,w,w,e)).
board(73,b(e,b,b,b,b,e,e,e,w,e,e,e,e,w,w,w)).
board(74,b(e,b,b,b,b,e,e,e,e,w,e,e,w,e,w,w)).
board(75,b(e,b,b,b,b,e,e,e,e,e,e,w,w,w,w,e)).
board(76,b(e,b,b,b,b,e,e,e,e,w,e,e,w,e,w,w)).
board(77,b(b,e,b,b,e,b,e,e,e,w,e,e,w,e,w,w)).
board(78,b(b,e,b,b,e,b,e,e,e,e,e,w,w,w,w,e)).
board(79,b(b,b,e,b,e,e,b,e,w,e,e,e,e,w,w,w)).
board(80,b(b,e,b,b,e,b,e,e,e,e,e,w,w,w,w,e)).
board(81,b(b,b,b,e,e,e,e,b,e,e,w,e,w,w,e,w)).
board(82,b(b,b,b,e,e,e,e,b,e,e,e,w,w,w,w,e)).
board(83,b(b,b,e,b,e,e,b,e,w,e,e,e,e,w,w,w)).
board(84,b(b,b,b,e,e,e,e,b,e,e,w,e,w,w,e,w)).
board(85,b(e,b,b,b,b,e,e,e,e,w,e,e,w,e,w,w)).
board(86,b(b,e,b,b,e,b,e,e,e,w,e,e,w,e,w,w)).
board(87,b(e,b,b,b,b,e,e,e,e,w,e,e,w,e,w,w)).
board(88,b(e,b,b,b,b,e,e,e,e,w,e,e,w,e,w,w)).
board(89,b(e,b,b,b,b,e,e,e,e,e,e,w,w,w,w,e)).
board(90,b(b,b,e,b,e,e,b,e,e,w,e,e,w,e,w,w)).
board(91,b(b,b,e,b,e,e,b,e,e,e,w,e,w,w,e,w)).
board(92,b(b,b,e,b,e,e,b,e,e,e,w,e,w,w,e,w)).
board(93,b(e,b,b,b,b,e,e,e,e,e,e,w,w,w,w,e)).
board(94,b(b,e,b,b,e,b,e,e,e,w,e,e,w,e,w,w)).
board(95,b(b,b,b,e,e,e,e,b,e,e,e,w,w,w,w,e)).
board(96,b(b,b,e,b,e,e,b,e,e,w,e,e,w,e,w,w)).
board(97,b(e,b,b,b,b,e,e,e,e,e,e,w,w,w,w,e)).
board(98,b(b,b,b,e,e,e,e,b,e,e,w,e,w,w,e,w)).
board(99,b(b,e,b,b,e,b,e,e,w,e,e,e,e,w,w,w)).
board(100,b(b,b,b,e,e,e,e,b,w,e,e,e,e,w,w,w)).
board(101,b(b,b,b,e,e,e,e,b,e,e,w,e,w,w,e,w)).
board(102,b(b,b,e,b,e,e,b,e,w,e,e,e,e,w,w,w)).
board(103,b(b,b,e,b,e,e,b,e,e,e,e,w,w,w,w,e)).
board(104,b(e,b,b,b,b,e,e,e,e,w,e,e,w,e,w,w)).
board(105,b(b,b,e,b,e,e,b,e,e,w,e,e,w,e,w,w)).
board(106,b(b,e,b,b,e,b,e,e,e,e,w,e,w,w,e,w)).
board(107,b(b,b,b,e,e,e,e,b,e,e,w,e,w,w,e,w)).
board(108,b(b,b,b,e,e,e,e,b,e,e,w,e,w,w,e,w)).
board(109,b(b,b,b,e,e,e,e,b,w,e,e,e,e,w,w,w)).
board(110,b(b,b,e,b,e,e,b,e,w,e,e,e,e,w,w,w)).
board(111,b(b,b,b,e,e,e,e,b,e,e,e,w,w,w,w,e)).
board(112,b(b,e,b,b,e,b,e,e,e,w,e,e,w,e,w,w)).
board(113,b(b,b,e,b,e,e,b,e,e,e,e,w,w,w,w,e)).
board(114,b(e,b,b,b,b,e,e,e,e,e,w,e,w,w,e,w)).
board(115,b(b,e,b,b,e,b,e,e,e,w,e,e,w,e,w,w)).
board(116,b(b,b,e,b,e,e,b,e,e,w,e,e,w,e,w,w)).
board(117,b(e,b,b,b,b,e,e,e,w,e,e,e,e,w,w,w)).
board(118,b(b,b,b,e,e,e,e,b,e,w,e,e,w,e,w,w)).
board(119,b(e,b,b,b,b,e,e,e,e,e,w,e,w,w,e,w)).
board(120,b(b,e,b,b,e,b,e,e,e,e,w,e,w,w,e,w)).
board(121,b(b,e,b,b,e,b,e,e,e,w,e,e,w,e,w,w)).
board(122,b(b,e,b,b,e,b,e,e,e,w,e,e,w,e,w,w)).
board(123,b(e,b,b,b,b,e,e,e,w,e,e,e,e,w,w,w)).
board(124,b(e,b,b,b,b,e,e,e,w,e,e,e,e,w,w,w)).
board(125,b(b,b,b,e,e,e,e,b,e,e,w,e,w,w,e,w)).
board(126,b(b,b,b,e,e,e,e,b,w,e,e,e,e,w,w,w)).
board(127,b(b,b,e,b,e,e,b,e,e,e,w,e,w,w,e,w)).
board(128,b(e,b,b,b,b,e,e,e,w,e,e,e,e,w,w,w)).
board(129,b(b,b,e,b,e,e,b,e,w,e,e,e,e,w,w,w)).
board(130,b(e,b,b,b,b,e,e,e,e,e,e,w,w,w,w,e)).
board(131,b(b,b,b,e,e,e,e,b,e,e,e,w,w,w,w,e)).
board(132,b(b,b,b,e,e,e,e,b,e,w,e,e,w,e,w,w)).
board(133,b(b,b,b,e,e,e,e,b,w,e,e,e,e,w,w,w)).
board(134,b(e,b,b,b,b,e,e,e,w,e,e,e,e,w,w,w)).
board(135,b(e,b,b,b,b,e,e,e,e,e,w,e,w,w,e,w)).
board(136,b(b,b,b,e,e,e,e,b,e,e,w,e,w,w,e,w)).
board(137,b(b,b,b,e,e,e,e,b,e,e,w,e,w,w,e,w)).
board(138,b(b,e,b,b,e,b,e,e,e,e,w,e,w,w,e,w)).
board(139,b(b,b,b,e,e,e,e,b,w,e,e,e,e,w,w,w)).
board(140,b(b,e,b,b,e,b,e,e,w,e,e,e,e,w,w,w)).
board(141,b(b,b,b,e,e,e,e,b,e,e,e,w,w,w,w,e)).
board(142,b(b,b,b,e,e,e,e,b,w,e,e,e,e,w,w,w)).
board(143,b(b,b,e,b,e,e,b,e,e,e,e,w,w,w,w,e)).
board(144,b(b,b,e,b,e,e,b,e,e,e,e,w,w,w,w,e)).
board(145,b(b,b,e,b,e,e,b,e,e,w,e,e,w,e,w,w)).
board(146,b(b,b,b,e,e,e,e,b,e,w,e,e,w,e,w,w)).
board(147,b(b,e,b,b,e,b,e,e,w,e,e,e,e,w,w,w)).
board(148,b(e,b,b,b,b,e,e,e,w,e,e,e,e,w,w,w)).
board(149,b(b,b,b,e,e,e,e,b,w,e,e,e,e,w,w,w)).
board(150,b(e,b,b,b,b,e,e,e,w,e,e,e,e,w,w,w)).
board(151,b(b,b,e,b,e,e,b,e,w,e,e,e,e,w,w,w)).
board(152,b(e,b,b,b,b,e,e,e,e,e,w,e,w,w,e,w)).
board(153,b(b,b,e,b,e,e,b,e,w,e,e,e,e,w,w,w)).
board(154,b(b,b,b,e,e,e,e,b,w,e,e,e,e,w,w,w)).
board(155,b(b,b,e,b,e,e,b,e,w,e,e,e,e,w,w,w)).
board(156,b(b,b,e,b,e,e,b,e,e,e,e,w,w,w,w,e)).
board(157,b(e,b,b,b,b,e,e,e,w,e,e,e,e,w,w,w)).
board(158,b(b,e,b,b,e,b,e,e,e,w,e,e,w,e,w,w)).
board(159,b(e,b,b,b,b,e,e,e,e,e,w,e,w,w,e,w)).
board(160,b(b,b,e,b,e,e,b,e,w,e,e,e,e,w,w,w)).
board(161,b(b,e,b,b,e,b,e,e,e,e,w,e,w,w,e,w)).
board(162,b(b,b,e,b,e,e,b,e,e,e,w,e,w,w,e,w)).
board(163,b(e,b,b,b,b,e,e,e,e,w,e,e,w,e,w,w)).
board(164,b(b,b,e,b,e,e,b,e,w,e,e,e,e,w,w,w)).
board(165,b(b,b,b,e,e,e,e,b,e,e,w,e,w,w,e,w)).
board(166,b(e,b,b,b,b,e,e,e,w,e,e,e,e,w,w,w)).
board(167,b(b,b,b,e,e,e,e,b,e,e,w,e,w,w,e,w)).
board(168,b(b,b,b,e,e,e,e,b,e,e,w,e,w,w,e,w)).
board(169,b(b,e,b,b,e,b,e,e,e,w,e,e,w,e,w,w)).
board(170,b(b,b,e,b,e,e,b,e,e,e,e,w,w,w,w,e)).
board(171,b(b,b,b,e,e,e,e,b,w,e,e,e,e,w,w,w)).
board(172,b(b,e,b,b,e,b,e,e,e,w,e,e,w,e,w,w)).
board(173,b(b,e,b,b,e,b,e,e,e,w,e,e,w,e,w,w)).
board(174,b(b,b,b,e,e,e,e,b,w,e,e,e,e,w,w,w)).
board(175,b(b,e,b,b,e,b,e,e,e,e,e,w,w,w,w,e)).
board(176,b(b,e,b,b,e,b,e,e,w,e,e,e,e,w,w,w)).
board(177,b(e,b,b,b,b,e,e,e,e,e,e,w,w,w,w,e)).
board(178,b(b,e,b,b,e,b,e,e,e,e,e,w,w,w,w,e)).
board(179,b(e,b,b,b,b,e,e,e,e,e,e,w,w,w,w,e)).
board(180,b(b,b,e,b,e,e,b,e,e,e,w,e,w,w,e,w)).
board(181,b(b,b,b,e,e,e,e,b,e,e,w,e,w,w,e,w)).
board(182,b(b,b,b,e,e,e,e,b,w,e,e,e,e,w,w,w)).
board(183,b(b,b,e,b,e,e,b,e,e,e,w,e,w,w,e,w)).
board(184,b(b,b,b,e,e,e,e,b,w,e,e,e,e,w,w,w)).
board(185,b(b,e,b,b,e,b,e,e,e,e,w,e,w,w,e,w)).
board(186,b(b,e,b,b,e,b,e,e,e,e,w,e,w,w,e,w)).
board(187,b(e,b,b,b,b,e,e,e,e,e,w,e,w,w,e,w)).
board(188,b(b,b,e,b,e,e,b,e,e,e,e,w,w,w,w,e)).
board(189,b(e,b,b,b,b,e,e,e,e,e,e,w,w,w,w,e)).
board(190,b(e,b,b,b,b,e,e,e,w,e,e,e,e,w,w,w)).
board(191,b(b,e,b,b,e,b,e,e,e,e,e,w,w,w,w,e)).
board(192,b(e,b,b,b,b,e,e,e,w,e,e,e,e,w,w,w)).
board(193,b(e,b,b,b,b,e,e,e,e,e,w,e,w,w,e,w)).
board(194,b(b,b,e,b,e,e,b,e,e,e,e,w,w,w,w,e)).
board(195,b(b,b,b,e,e,e,e,b,e,e,e,w,w,w,w,e)).
board(196,b(b,b,e,b,e,e,b,e,e,w,e,e,w,e,w,w)).
board(197,b(b,b,e,b,e,e,b,e,e,e,e,w,w,w,w,e)).
board(198,b(b,b,e,b,e,e,b,e,w,e,e,e,e,w,w,w)).
board(199,b(b,b,b,e,e,e,e,b,e,w,e,e,w,e,w,w)).
