
next_pos1( b, 1, [b,b,b,w,e,e,e,w,w],[b,e,b,b,e,e,e,w,w],draw).
next_pos1( b, 1, [b,b,b,e,w,e,w,e,w],[e,b,b,e,b,e,w,e,w],draw).
next_pos1( w, 1, [b,e,b,b,e,e,e,w,w],[b,e,b,w,e,e,e,e,w],draw).
next_pos1( w, 1, [b,e,b,w,b,e,e,w,w],[b,e,b,w,w,e,e,w,e],draw).
next_pos1( w, 1, [b,b,e,w,e,b,e,w,w],[b,w,e,e,e,b,e,w,w],win).
next_pos1( w, 1, [e,b,b,b,w,e,w,e,w],[e,b,w,b,e,e,w,e,w],win).
next_pos1( w, 1, [e,b,b,e,b,e,w,e,w],[e,b,b,e,w,e,e,e,w],draw).
next_pos1( b, 2, [b,e,b,w,e,e,e,e,w],[b,e,e,w,e,b,e,e,w],draw).
next_pos1( b, 2, [b,e,b,b,w,e,e,e,w],[b,e,b,e,w,e,b,e,w],loose).
next_pos1( b, 2, [b,e,b,b,e,w,e,w,e],[b,e,b,e,e,w,e,b,e],loose).
next_pos1( b, 2, [b,e,b,w,w,e,e,w,e],[b,e,e,w,b,e,e,w,e],draw).
next_pos1( b, 2, [b,e,b,w,b,w,e,w,e],[],draw).
next_pos1( b, 2, [b,w,e,e,e,b,e,w,w],[],win).
next_pos1( b, 2, [b,b,e,w,w,b,e,e,w],[e,b,e,w,b,b,e,e,w],win).
next_pos1( b, 2, [b,b,e,w,e,w,e,e,w],[b,e,e,w,e,b,e,e,w],draw).
next_pos1( b, 2, [e,b,w,b,e,e,w,e,w],[],win).
next_pos1( b, 2, [e,b,b,w,b,e,e,e,w],[e,b,b,w,e,e,e,e,b],loose).
next_pos1( b, 2, [e,b,b,e,w,e,e,e,w],[e,b,e,e,b,e,e,e,w],draw).
next_pos1( b, 2, [e,b,b,e,w,e,w,e,e],[e,b,e,e,b,e,e,e,w],draw).
next_pos1( b, 2, [e,b,b,e,b,w,w,e,e],[e,b,b,e,e,w,b,e,e],loose).
next_pos1( w, 3, [b,e,e,w,e,b,e,e,w],[],draw).
next_pos1( w, 3, [e,e,b,b,b,e,e,e,w],[e,e,b,b,w,e,e,e,e],loose).
next_pos1( w, 3, [b,e,e,b,b,e,e,e,w],[b,e,e,b,w,e,e,e,e],loose).
next_pos1( w, 3, [b,e,e,b,w,b,e,e,w],[w,e,e,b,e,b,e,e,w],win).
next_pos1( w, 3, [b,e,b,e,w,e,b,e,w],[],loose).
next_pos1( w, 3, [b,e,b,e,e,w,b,w,e],[],loose).
next_pos1( w, 3, [b,e,b,e,e,w,e,b,e],[],loose).
next_pos1( w, 3, [e,e,b,w,b,e,e,w,e],[w,e,b,e,b,e,e,w,e],win).
next_pos1( w, 3, [b,e,e,w,b,e,e,w,e],[],draw).
next_pos1( w, 3, [b,e,e,w,w,b,e,w,e],[w,e,e,w,e,b,e,w,e],win).
next_pos1( w, 3, [e,b,e,w,b,b,e,e,w],[e,w,e,e,b,b,e,e,w],win).
next_pos1( w, 3, [b,e,e,b,e,w,e,e,w],[b,e,w,b,e,e,e,e,w],win).
next_pos1( w, 3, [b,e,e,w,b,w,e,e,w],[b,e,w,w,b,e,e,e,w],win).
next_pos1( w, 3, [e,b,b,w,e,e,e,b,w],[],loose).
next_pos1( w, 3, [e,b,b,w,e,e,e,e,b],[],loose).
next_pos1( w, 3, [e,b,e,e,b,e,e,e,w],[e,b,e,e,w,e,e,e,e],draw).
next_pos1( w, 3, [e,b,e,e,w,b,e,e,w],[],draw).
next_pos1( w, 3, [e,b,e,e,w,b,w,e,e],[],win).
next_pos1( w, 3, [e,b,b,e,e,w,b,e,e],[],loose).
next_pos1( w, 3, [e,b,b,e,e,w,w,b,e],[],loose).
next_pos1( b, 4, [e,e,b,b,w,e,e,e,e],[e,e,b,e,w,e,b,e,e],loose).
next_pos1( b, 4, [e,e,b,b,b,w,e,e,e],[],loose).
next_pos1( b, 4, [b,e,e,b,w,e,e,e,e],[b,e,e,e,w,e,b,e,e],loose).
next_pos1( b, 4, [b,e,e,b,b,w,e,e,e],[b,e,e,e,b,w,b,e,e],loose).
next_pos1( b, 4, [w,e,e,b,e,b,e,e,w],[],win).
next_pos1( b, 4, [b,w,e,b,e,b,e,e,w],[],win).
next_pos1( b, 4, [w,e,b,e,b,e,e,w,e],[],win).
next_pos1( b, 4, [w,e,e,w,e,b,e,w,e],[],win).
next_pos1( b, 4, [b,w,e,w,e,b,e,w,e],[],win).
next_pos1( b, 4, [b,e,e,w,w,w,e,e,e],[e,e,e,w,b,w,e,e,e],win).
next_pos1( b, 4, [w,b,e,e,b,b,e,e,w],[],win).
next_pos1( b, 4, [e,w,e,e,b,b,e,e,w],[],win).
next_pos1( b, 4, [e,b,e,w,w,b,e,e,e],[e,b,e,w,w,e,e,e,b],win).
next_pos1( b, 4, [b,e,w,b,e,e,e,e,w],[],win).
next_pos1( b, 4, [b,e,w,w,b,e,e,e,w],[],win).
next_pos1( b, 4, [e,b,e,e,w,e,e,e,e],[],draw).
next_pos1( b, 4, [e,b,e,e,b,w,e,e,e],[e,b,e,e,e,w,e,b,e],loose).
next_pos1( w, 5, [e,e,e,b,b,e,e,e,e],[],draw).
next_pos1( w, 5, [e,e,e,b,w,b,e,e,e],[e,w,e,b,e,b,e,e,e],win).
next_pos1( w, 5, [e,e,b,e,w,e,b,e,e],[],loose).
next_pos1( w, 5, [e,e,b,e,b,w,b,e,e],[],loose).
next_pos1( w, 5, [e,e,b,b,e,w,e,b,e],[],loose).
next_pos1( w, 5, [b,e,e,e,w,e,b,e,e],[],loose).
next_pos1( w, 5, [b,e,e,e,b,w,b,e,e],[],loose).
next_pos1( w, 5, [b,e,e,b,e,w,e,b,e],[],loose).
next_pos1( w, 5, [e,e,e,w,b,w,e,e,e],[w,e,e,e,b,w,e,e,e],win).
next_pos1( w, 5, [e,b,e,w,w,e,e,e,b],[],loose).
next_pos1( w, 5, [e,b,e,e,e,w,e,b,e],[],loose).
next_pos1( b, 5, [e,w,e,b,e,b,e,e,e],[],win).
next_pos1( b, 5, [w,e,e,e,b,w,e,e,e],[],win).
